routes/web.php
<?php

use App\Http\Controllers\AuthController;

// Admin Route

use App\Http\Controllers\Admin\{
    DashboardController,
    MemberController,
    SubscriptionController,
    TemplateController,
    UserController
};

// End Admin Route

// Member Route

use App\Http\Controllers\Member\{
    DashboardController as MemberDashboardController
};

// End Member Route

use Illuminate\Support\Facades\Route;

Route::get('login', [AuthController::class, 'index'])->name('login');
Route::post('login', [AuthController::class, 'login'])->name('store.login');

Route::get('register', [AuthController::class, 'register'])->name('register');
Route::post('register', [AuthController::class, 'store_register'])->name('store.register');


Route::middleware(['auth'])->group(function() {

    Route::prefix('admin')->group(function() {
        Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard.index');
        Route::resource('member', MemberController::class);
        Route::post('member/list', [MemberController::class, 'list'])->name('member.list');
        Route::resource('user', UserController::class);
        Route::post('user/list', [UserController::class, 'list'])->name('user.list');
        Route::resource('subscription', SubscriptionController::class);
        Route::resource('template', TemplateController::class);
    });

    Route::prefix('member')->group(function() {
        Route::get('/dashboard', [MemberDashboardController::class, 'index'])->name('dashboard.index');
    });
    
});

Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

resources/views/admin/template/create.blade.php
{!! eform_open('form') !!}
<div class="form-group">
    {!! eform_input('text', 'Name', 'name') !!}
</div>

<div class="form-group">
    {!! eform_input('text', 'Price', 'price') !!}
</div>

<div class="form-group">
    {!! eform_area('Description', 'description') !!}
</div>

{!! eform_close() !!}

resources/views/admin/template/edit.blade.php
{!! eform_open('form') !!}
@method('PUT')
<div class="form-group">
    {!! eform_input('text', 'Name', 'name', $subscription->name) !!}
</div>

<div class="form-group">
    {!! eform_input('text', 'Price', 'price', number_format($subscription->price,0,',','.')) !!}
</div>

<div class="form-group">
    {!! eform_area('Description', 'description', $subscription->description) !!}
</div>

{!! eform_close() !!}

resources/views/admin/template/index.blade.php
@extends('layout')
@section('content')
    <section class="section">
        <div class="row">
            <div class="col-lg-10">
                <div class="title-box">{{ $title }}</div>
            </div>
            <div class="col-lg-2">
                <div class="pull-right">
                    <a href="javascript:;" onclick="btnAdd()" class="btn btn-sm btn-success">
                        <i class="fa fa-plus"></i>
                        Create New
                    </a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover mb-0">
                                <thead>
                                    <tr>
                                        <th style="width: 3%;">No</th>
                                        <th style="width: 15%;">Name</th>
                                        <th>Description</th>
                                        <th style="width: 7%;">Subscriptions</th>
                                        <th style="width: 7%;">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($templates as $key => $template)
                                        <tr>
                                            <td class="text-center">{{ $key+1 }}</td>
                                            <td>{{ $template->name }}</td>
                                            <td>{{ $template->description }}</td>
                                            <td>
                                                @isset($template->subscriptions)
                                                    @foreach ($template->subscriptions as $sub)
                                                        {{ $sub->subscription->name }}
                                                    @endforeach
                                                    
                                                @endisset
                                            </td>
                                            <td class="text-center">
                                                <a class="btn btn-xs btn-success" href="javascript:;" onclick="btnEdit('{{ $template->id }}')"><i class="fa fa-edit"></i></a>
                                                <a class="btn btn-xs btn-danger" href="javascript:;" onclick="btnDelete('{{ $template->id }}')"><i class="fa fa-trash"></i></a>
                                            </td>
                                        </tr>
                                    @empty
                                        <tr>
                                            <td colspan="5" class="text-center">No data available.</td>
                                        </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@push('js')
<script>
    function btnAdd() {
        Modal.create('Create New Role', 'modal-lg')
        $.get(`{{ route('subscription.create') }}`, function(data) {
            Modal.html(data)

            $(".btn-simpan").on('click', function(e) {
                e.preventDefault()

                var form = $('#form')

                $("button").attr('disabled', true)

                $.ajax({
                    url: `{{ route('subscription.store') }}`,
                    type: 'post',
                    dataType: 'json',
                    data: form.serializeArray(),
                    success: function(result) {
                        if (result.status == true) {
                            show_success(result.response)
                            setTimeout(() => {
                                window.location.reload()
                            }, 1000)
                        } else {
                            show_failed(result.response)
                            $("button").removeAttr('disabled')
                        }
                    },
                    error: function(result) {
                        $("button").removeAttr('disabled')
                        show_errors(result.responseJSON)
                    }
                })
            })
        })
    }

    function btnEdit(id) {
        Modal.create('Edit Role', 'modal-lg')

        var url = '{{ route('subscription.edit', ':id') }}'
        url = url.replace(':id', id)
        $.get(`${url}`, function(data) {
            Modal.html(data)

            $(".btn-simpan").on('click', function(e) {
                e.preventDefault()

                var form = $('#form')

                $("button").attr('disabled', true)

                var url = '{{ route('subscription.update', ':id') }}'
                    url = url.replace(':id', id)

                $.ajax({
                    url: `${url}`,
                    type: 'post',
                    dataType: 'json',
                    data: form.serializeArray(),
                    success: function(result) {
                        if (result.status == true) {
                            show_success(result.response)
                            setTimeout(() => {
                                window.location.reload()
                            }, 1000)
                        } else {
                            show_failed(result.response)
                            $("button").removeAttr('disabled')
                        }
                    },
                    error: function(result) {
                        $("button").removeAttr('disabled')
                        show_errors(result.responseJSON)
                    }
                })
            })
        })
    }

    function btnDelete(id) {
        var url = '{{ route('subscription.destroy', ':id') }}'
        url = url.replace(':id', id)
        Swal.fire({
            title: 'Confirmation',
            text: "Are you sure delete this data?",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes, delete it!',
            cancelButtonText: 'No, cancel!',
            reverseButtons: true
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    url: `${url}`,
                    type: 'post',
                    dataType: 'json',
                    data: { _method: 'DELETE' },
                    success: function(result) {
                        if (result.status == true) {
                            show_success(result.response)
                            setTimeout(() => {
                                window.location.reload()
                            }, 1000)
                        } else {
                            show_failed(result.response)
                        }
                    },
                    error: function(result) {
                        show_errors(result.responseJSON)
                    }
                })
            } else {
                return false
            }
        })
    }
</script>
@endpush