routes/web.php
<?php

use App\Http\Controllers\AuthController;

// Admin Route

use App\Http\Controllers\Admin\{
    DashboardController,
    MemberController,
    SubscriptionController,
    TemplateController,
    UserController
};

// End Admin Route

// Member Route

use App\Http\Controllers\Member\{
    DashboardController as MemberDashboardController
};

// End Member Route

use Illuminate\Support\Facades\Route;

Route::get('login', [AuthController::class, 'index'])->name('login');
Route::post('login', [AuthController::class, 'login'])->name('store.login');

Route::get('register', [AuthController::class, 'register'])->name('register');
Route::post('register', [AuthController::class, 'store_register'])->name('store.register');


Route::middleware(['auth'])->group(function() {

    Route::prefix('admin')->group(function() {
        Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard.index');
        Route::resource('member', MemberController::class);
        Route::post('member/list', [MemberController::class, 'list'])->name('member.list');
        Route::resource('user', UserController::class);
        Route::post('user/list', [UserController::class, 'list'])->name('user.list');
        Route::resource('subscription', SubscriptionController::class);
        Route::resource('template', TemplateController::class);
    });

    Route::prefix('member')->group(function() {
        Route::get('/dashboard', [MemberDashboardController::class, 'index'])->name('dashboard.index');
    });
    
});

Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

app/Http/Controllers/Admin/MemberController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;

class MemberController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $title = 'List Member';
        return view('admin.member.index', compact('title'));
    }

    public function list(Request $request)
    {
        $data = [];

        $no = intval($request['start']);
        $start = intval($request['start']);
        $length = intval($request['length']);
        $filter = "";

        if ( isset($request['start']) && $request['length'] != -1 ) {

            $start = intval($request['start']);
            $length = intval($request['length']);
        }

        if ( isset($request['search']) && $request['search']['value'] != '' ) {
            $filter = trim($request['search']['value']);
        }

        $users = User::where('role', '=', 'user')->orderBy('id','asc')
                ->skip($start)
                ->take($length)
                ->get();
                
        $total_record_filter = User::where('role', '=', 'user')->count();
                                
        $data = [];

        foreach ($users as $value) {
            ++$no;
            $value->no = $no;
            $data[] = $value;    
        }

        return response()->json([
            "draw"            => isset ( $request['draw'] ) ? intval( $request['draw'] ) : 0,
            "recordsTotal"    => $total_record_filter,
            "recordsFiltered" => $total_record_filter,
            'data' => $data
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::where('role', '=', 'user')->findOrFail($id);
        if($user->delete()) {
            return response()->json([
                'status'    => true,
                'response'  => 'Member berhasil dihapus.'
            ]);
        } else {
            return response()->json([
                'status'    => false,
                'response'  => 'Member gagal dihapus.'
            ]);
        }
    }
}

app/Http/Controllers/Member/DashboardController.php
<?php

namespace App\Http\Controllers\Member;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        $title = 'Dashboard';
        return view('member.dashboard.index', compact('title'));
    }
}

resources/views/admin/member/index.blade.php
@extends('layout')
@section('content')
    <section class="section">
        <div class="row">
            <div class="col-lg-10">
                <div class="title-box">{{ $title }}</div>
            </div>
            <div class="col-lg-2">
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                @if(session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
                @endif
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover mb-0">
                                <thead>
                                    <tr>
                                        <th style="width: 3%;">No</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th style="width: 7%;">Action</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@push('js')
<script>


    var table = $('.table').DataTable({
        ordering: false,
        serverSide: true,
        processing: true,
        responsive: true,
        stateSave: true,
        ajax: {
            url: `{{ route('member.list') }}`,
            type: 'post',
        },
        columns: [
            { "data": "no", sClass:"text-center" },
            { "data": "name" },
            { "data": "email" },
            { "data": null, sClass:"text-center", render: function(data, type, row, meta) {
                var url_edit = `{{ route('member.edit', ':id') }}`
                url_edit = url_edit.replace(':id', data.id)

                var url_hapus = `{{ route('member.destroy', ':id') }}`
                url_hapus = url_hapus.replace(':id', data.id)

                return `
                        <a class="btn btn-xs btn-danger" href="javascript:;" onclick="btnDelete('${url_hapus}')"><i class="fa fa-trash"></i></a>
                    `
            } },
        ],
        initComplete: function() {
            var api = this.api();
            $("input[type='search']")
                .off(".DT")
                .on("keyup.DT, blur", function(e) {
                    if (e.keyCode === 13) {
                        api.search(this.value).draw();
                    }
                });
            $("input[type='search']").attr('placeholder', 'Press Enter to search')
        },
    })

    const btnDelete = (deleted) => {
        Swal.fire({
            title: 'Confirmation',
            text: "Are you sure delete this data?",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes, delete it!',
            cancelButtonText: 'No, cancel!',
            reverseButtons: true
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    url: `${deleted}`,
                    type: 'post', 
                    data: {
                        _method: 'DELETE',
                    },
                    dataType: 'json',
                    success: function(res) {
                        if (res.status == true) {
                            show_success(res.response)
                            table.ajax.reload()
                        } else {
                            show_failed(res.response)
                        }
                    },
                    error: function(error) {
                        show_errors(error.responseJSON)
                    }
                })
            } else {
                return false
            }
        })
    }
</script>
@endpush