routes/web.php
<?php

use App\Http\Controllers\AuthController;

// Admin Route

use App\Http\Controllers\Admin\{
    DashboardController,
    MemberController,
    SubscriptionController,
    TemplateController,
    UserController
};

// End Admin Route

// Member Route

use App\Http\Controllers\Member\{
    DashboardController as MemberDashboardController
};

// End Member Route

use Illuminate\Support\Facades\Route;

Route::get('login', [AuthController::class, 'index'])->name('login');
Route::post('login', [AuthController::class, 'login'])->name('store.login');

Route::get('register', [AuthController::class, 'register'])->name('register');
Route::post('register', [AuthController::class, 'store_register'])->name('store.register');


Route::middleware(['auth'])->group(function() {

    Route::prefix('admin')->group(function() {
        Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard.index');
        Route::resource('member', MemberController::class);
        Route::post('member/list', [MemberController::class, 'list'])->name('member.list');
        Route::resource('user', UserController::class);
        Route::post('user/list', [UserController::class, 'list'])->name('user.list');
        Route::resource('subscription', SubscriptionController::class);
        Route::resource('template', TemplateController::class);
    });

    Route::prefix('member')->group(function() {
        Route::get('/dashboard', [MemberDashboardController::class, 'index'])->name('dashboard.index');
    });
    
});

Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $title = 'List User';
        return view('admin.user.index', compact('title'));
    }

    public function list(Request $request)
    {
        $data = [];

        $no = intval($request['start']);
        $start = intval($request['start']);
        $length = intval($request['length']);
        $filter = "";

        if ( isset($request['start']) && $request['length'] != -1 ) {

            $start = intval($request['start']);
            $length = intval($request['length']);
        }

        if ( isset($request['search']) && $request['search']['value'] != '' ) {
            $filter = trim($request['search']['value']);
        }

        $users = User::where('role', '=', 'admin')->orderBy('id','asc')
                ->skip($start)
                ->take($length)
                ->get();
                
        $total_record_filter = User::where('role', '=', 'admin')->count();
                                
        $data = [];

        foreach ($users as $value) {
            ++$no;
            $value->no = $no;
            $data[] = $value;    
        }

        return response()->json([
            "draw"            => isset ( $request['draw'] ) ? intval( $request['draw'] ) : 0,
            "recordsTotal"    => $total_record_filter,
            "recordsFiltered" => $total_record_filter,
            'data' => $data
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $title = 'Create New User';
        return view('admin.user.create', compact('title'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'  => 'required',
            'email' => 'required|email|unique:users,email',
            'password'              => 'required|confirmed',
            'password_confirmation' => 'required'
        ]);

        $user = new User;
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = bcrypt($request->password);
        $user->email_verified_at = Carbon::now();
        $user->role = 'admin';
        if ($user->save()) {
            return redirect()->route('user.index')->with(['success' => 'Add user success.']);
        } else { 
            return redirect()->route('user.create')->withInput()->withErrors(['failed' => 'Something wrong. Try again later.']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $title = 'Edit User';
        $user = User::findOrFail($id);
        return view('admin.user.edit', compact('user', 'title'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $title = 'Edit User';
        $user = User::findOrFail($id);
        return view('admin.user.edit', compact('user', 'title'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'  => 'required',
            'email' => 'required|email|unique:users,email,' . $id . '',
            'password'              => 'confirmed',
            'password_confirmation' => ''
        ]);

        $user = User::findOrFail($id);
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = empty($request->password) ? $user->password : bcrypt($request->password);
        $user->role = 'admin';
        if ($user->save()) {
            return redirect()->route('user.index')->with(['success' => 'Update user success.']);
        } else { 
            return redirect()->route('user.create')->withInput()->withErrors(['failed' => 'Something wrong. Try again later.']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        if ($user->delete()) {
            return response()->json(['status' => true, 'response' => 'Delete user success.'], 200);
        } else {
            return response()->json(['status' => false, 'response' => 'Something wrong. Try again later.'], 422);
        }
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/user/create.blade.php
@extends('layout')
@section('content')
    <section class="section">
        <div class="row">
            <div class="col-lg-12">
                <div class="title-box">{{ $title }}</div>
            </div>
            
        </div>

        <div class="row">
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-body">
                        @if(session('error'))
                        <div class="alert alert-danger">
                            {{ session('error') }}
                        </div>
                        @endif
                        <form method="post" action="{{ route('user.store') }}">
                            @csrf

                            <div class="form-group">
                                {!! eform_input('text', 'Name', 'name', old('name')) !!}
                                @error('name')
                                    <div class="is-invalid">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                {!! eform_input('email', 'Email', 'email', old('email')) !!}
                                @error('email')
                                    <div class="is-invalid">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                {!! eform_input('password', 'Password', 'password') !!}
                                @error('password')
                                    <div class="is-invalid">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                {!! eform_input('password', 'Password Confirmation', 'password_confirmation') !!}
                                @error('password_confirmation')
                                    <div class="is-invalid">{{ $message }}</div>
                                @enderror
                            </div>

                            <div>
                                <button onclick="window.location.href = '{{ route('user.index') }}'" class="btn btn-danger">
                                    Kembali
                                </button>
                                <button type="submit" class="btn btn-primary">
                                    Simpan
                                </button>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
@push('js')
<script>

    $('form').on('submit', function() {
        $('button').attr('disabled', true)
    })
</script>
@endpush

resources/views/admin/user/edit.blade.php
@extends('layout')
@section('content')
    <section class="section">
        <div class="row">
            <div class="col-lg-12">
                <div class="title-box">{{ $title }}</div>
            </div>
            
        </div>

        <form method="post" action="{{ route('user.update', $user->id) }}">
            @method('PUT')
            @csrf
            {!! eform_hidden('id', $user->id) !!}
            <div class="row">
                <div class="col-lg-6">
                    <div class="card">
                        <div class="card-body">
                            @if(session('error'))
                            <div class="alert alert-danger">
                                {{ session('error') }}
                            </div>
                            @endif

                            <div class="form-group">
                                {!! eform_input('text', 'Name', 'name', $user->name) !!}
                                @error('name')
                                    <div class="is-invalid">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                {!! eform_input('email', 'Email', 'email', $user->email) !!}
                                @error('email')
                                    <div class="is-invalid">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                {!! eform_input('password', 'Password', 'password', '', '') !!}
                                @error('password')
                                    <div class="is-invalid">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                {!! eform_input('password', 'Password Confirmation', 'password_confirmation', '', '') !!}
                                @error('password_confirmation')
                                    <div class="is-invalid">{{ $message }}</div>
                                @enderror
                            </div>

                            <div>
                                <button onclick="window.location.href = '{{ route('user.index') }}'" class="btn btn-danger">
                                    Kembali
                                </button>
                                <button type="submit" class="btn btn-primary">
                                    Simpan
                                </button>
                            </div>

                        </div>
                    </div>
                </div>

            </div>
        </form>
    </section>
@endsection

@push('js')
<script>
    $('form').on('submit', function() {
        $('button').attr('disabled', true)
    })
    
</script>
@endpush

resources/views/admin/user/index.blade.php
@extends('layout')
@section('content')
    <section class="section">
        <div class="row">
            <div class="col-lg-10">
                <div class="title-box">{{ $title }}</div>
            </div>
            <div class="col-lg-2">
                <div class="pull-right">
                    <a href="{{ route('user.create') }}" class="btn btn-sm btn-success">
                        <i class="fa fa-plus"></i>
                        Create New
                    </a>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-lg-12">
                @if(session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
                @endif
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover mb-0">
                                <thead>
                                    <tr>
                                        <th style="width: 3%;">No</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th style="width: 7%;">Action</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@push('js')
<script>

    const btnDelete = (deleted) => {
        Swal.fire({
            title: 'Confirmation',
            text: "Are you sure delete this data?",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes, delete it!',
            cancelButtonText: 'No, cancel!',
            reverseButtons: true
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    url: `${deleted}`,
                    type: 'post', 
                    data: {
                        _method: 'DELETE',
                    },
                    dataType: 'json',
                    success: function(res) {
                        if (res.status == true) {
                            show_success(res.response)
                            table.ajax.reload()
                        } else {
                            show_failed(res.response)
                        }
                    },
                    error: function(error) {
                        show_errors(error.responseJSON)
                    }
                })
            } else {
                return false
            }
        })
    }

    var table = $('.table').DataTable({
        ordering: false,
        serverSide: true,
        processing: true,
        responsive: true,
        stateSave: true,
        ajax: {
            url: `{{ route('user.list') }}`,
            type: 'post',
        },
        columns: [
            { "data": "no", sClass:"text-center" },
            { "data": "name" },
            { "data": "email" },
            { "data": null, sClass:"text-center", render: function(data, type, row, meta) {
                var url_edit = `{{ route('user.edit', ':id') }}`
                url_edit = url_edit.replace(':id', data.id)

                var url_hapus = `{{ route('user.destroy', ':id') }}`
                url_hapus = url_hapus.replace(':id', data.id)
                return `
                        <a class="btn btn-xs btn-success" href="${url_edit}"><i class="fa fa-edit"></i></a>
                        <a class="btn btn-xs btn-danger" href="javascript:;" onclick="btnDelete('${url_hapus}')"><i class="fa fa-trash"></i></a>
                    `
            } },
        ],
        initComplete: function() {
            var api = this.api();
            $("input[type='search']")
                .off(".DT")
                .on("keyup.DT, blur", function(e) {
                    if (e.keyCode === 13) {
                        api.search(this.value).draw();
                    }
                });
            $("input[type='search']").attr('placeholder', 'Press Enter to search')
        },
    })
</script>
@endpush

resources/views/admin/user/show.blade.php
@extends('backend.layout')
@push('css')
<link rel="stylesheet" href="{{ asset('assets/plugins/leaflet/leaflet.css') }}">
@endpush
@section('content')
    <section class="section">
        <div class="row">
            <div class="col-lg-12">
                <div class="title-box">{{ $title }}</div>
            </div>
            
        </div>

        <form method="post" action="{{ route('update.profil', ['id' => auth()->user()->id]) }}">
            @method('put')
            @csrf
            {!! eform_hidden('id', auth()->user()->id) !!}
            <div class="row">
                <div class="col-lg-6">
                    <div class="card">
                        <div class="card-body">
                            @if(session('success'))
                            <div class="alert alert-success">
                                {{ session('success') }}
                            </div>
                            @endif
                            @if(session('error'))
                            <div class="alert alert-danger">
                                {{ session('error') }}
                            </div>
                            @endif

                            <div class="form-group text-center">
                                <div class=" d-flex justify-content-center align-items-center">
                                    <a href="{{ show_photo_user(auth()->user()->id) }}" class="text-decoration-none" target="_blank" rel="noopener noreferrer">
                                        <div class="shadow image1" style="border-radius:100%;background-image: url('{{ show_photo_user(auth()->user()->id) }}');width:170px;height:170px;background-size:cover;background-position:center"></div>
                                        <div class="mt-2">
                                            @if (auth()->user()->email_verified_at <> null)
                                                <strong class=" text-success"><i class="fa fa-check-circle"></i> Terverifikasi</strong>
                                            @else
                                                <strong class=" text-danger">Belum diverifikasi</strong>
                                            @endif
                                        </div>
                                    </a>
                                </div>
                                <div class="text-center">
                                    <a href="javascript:;" onclick="changePhoto()">Ganti foto</a>
                                    <input type="hidden" name="foto" id="foto">
                                </div>
                            </div>

                            <div class="form-group">
                                {!! eform_input('text', 'Name', 'name', auth()->user()->name) !!}
                                @error('name')
                                    <div class="is-invalid">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                {!! eform_input('text', 'NIK', 'nik', auth()->user()->nik, 'maxlength="16" onkeyup="number($(this))" required') !!}
                                @error('nik')
                                    <div class="is-invalid">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                {!! eform_input('email', 'Email', 'email', auth()->user()->email) !!}
                                @error('email')
                                    <div class="is-invalid">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                {!! eform_input('text', 'Phone', 'phone', auth()->user()->phone, 'onkeyup="number($(this))" maxlength="13" required') !!}
                                @error('phone')
                                    <div class="is-invalid">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                {!! eform_input('text', 'Address', 'address', auth()->user()->address, '', '') !!}
                            </div>

                            <div class="form-group">
                                {!! eform_select_all('Kecamatan', 'kecamatan', $district, auth()->user()->district_id, $disable, '') !!}
                            </div>

                            <div class="form-group">
                                {!! eform_select_all('Desa', 'desa', $village, auth()->user()->village_id, $disable, '') !!}
                            </div>

                            <div class="form-group">
                                {!! eform_input('password', 'Password', 'password', '', '') !!}
                                @error('password')
                                    <div class="is-invalid">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                {!! eform_input('password', 'Password Confirmation', 'password_confirmation', '', '') !!}
                                @error('password_confirmation')
                                    <div class="is-invalid">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="text-center">
                                <button type="submit" class="btn btn-primary">
                                    Simpan Perubahan
                                </button>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="card">
                        <div class="card-header">
                            <h6 class="mb-0">Lokasi</h6>
                        </div>
                        <div class="card-body" style="padding: 0 !important;overflow:hidden;">
                            <div style="width: 100%;height:50vh;" id="map"></div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </section>
@endsection

@push('js')
<script src="{{ asset('assets/plugins/leaflet/leaflet.js') }}"></script>
<script src="{{ asset('assets/plugins/webcamjs/webcam.min.js') }}"></script>
<script>
    $('#kecamatan').on('change', function() {

        $('#desa').empty().html(`<option value="0">Semua Desa</option>`)

        $.post(`{{ route('json.village') }}`, { district: $('#kecamatan').val() }).then((response) => {
            var option = ``
            if (response.data.length > 0) {
                option += `<option value="0">Pilih Desa</option>`
                response.data.forEach(function(element, index) {
                    option += `<option value="${element.id}">${element.name}</option>`
                });
            } else {
                option += `<option value="0">Data Desa Kosong</option>`
            }
            $('#desa').html(option)
        }).catch((error) => {
            console.log(error)
        })

    });

    Webcam.set({
        width: 320,
        height: 240,
        image_format: 'jpeg',
        jpeg_quality: 90
    });

    const take_snapshot = () => {

        Webcam.snap(function (data_uri) {

            $('.image1').css({
                'background-image' : `url('${data_uri}')`
            })
            $('#foto').val(data_uri)
        });

        Webcam.reset();
        Modal.close()
    }

    const changePhoto = () => {
        Modal.createNoFooter('Ambil Foto', 'modal-md')
        Modal.html(`
            <div class="text-center mb-3">Tunggu sampai kamera terbuka</div>
            <div class="d-flex justify-content-center align-items-center">
                <div id="my_camera"></div>
            </div>
            <div class="text-center mt-3 take-img d-none"><button class="btn btn-info" type=button onclick="take_snapshot()"><i class="fa fa-camera"></i> Ambil foto</button></div>
        `)
        Webcam.attach('#my_camera');

        navigator.mediaDevices.getUserMedia({
                video: true
            })
            .then(stream => {
                if(stream.active == true) {
                    $('.take-img').removeClass("d-none")
                }
            })
            .then(() => $('.take-img').removeClass("d-none"))
            .catch(error => {
                $('.take-img').addClass("d-none")
                alert(error)
            });

    }

    $('form').on('submit', function () {
        $('button').attr('disabled', true)
    })

    var map = L.map('map').setView([{{ auth()->user()->latitude ?? config('app.default_lat') }}, {{ auth()->user()->longitude ?? config('app.default_long') }}], {{ intval(config('app.default_zoom')) }});

    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);

    L.marker([{{ auth()->user()->latitude ?? config('app.default_lat') }}, {{ auth()->user()->longitude ?? config('app.default_long') }}]).addTo(map)
        .bindPopup('{{ auth()->user()->name }}')
        .openPopup();
</script>
@endpush